### ISSUE TITLE
Error installing huggingface_sb3

### ISSUE THREAD

**Issue by kirilllzaitsev** [huggingface/huggingface_sb3#9]
Hi! I'm running this notebook https://github.com/huggingface/deep-rl-class/blob/main/unit1/unit1.ipynb from your DRL series. Installation of some libraries is causing some issues. For huggingface_sb3, it is:
```
Collecting huggingface_sb3
  Using cached huggingface_sb3-2.0.0-py3-none-any.whl (7.4 kB)
Requirement already satisfied: wasabi in ./rl/lib/python3.8/site-packages (from huggingface_sb3) (0.9.1)
Collecting cloudpickle==1.6
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting huggingface-hub
  Using cached huggingface_hub-0.6.0-py3-none-any.whl (84 kB)
Collecting pickle5
  Using cached pickle5-0.0.11.tar.gz (132 kB)
  Preparing metadata (setup.py) ... done
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: packaging>=20.9 in ./rl/lib/python3.8/site-packages (from huggingface-hub->huggingface_sb3) (21.3)
Collecting filelock
  Using cached filelock-3.7.0-py3-none-any.whl (10 kB)
Collecting tqdm
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./rl/lib/python3.8/site-packages (from packaging>=20.9->huggingface-hub->huggingface_sb3) (3.0.9)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Using legacy 'setup.py install' for pickle5, since package 'wheel' is not installed.
Installing collected packages: pickle5, certifi, urllib3, typing-extensions, tqdm, pyyaml, idna, filelock, cloudpickle, charset-normalizer, requests, huggingface-hub, huggingface_sb3
  Running setup.py install for pickle5 ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pickle5 did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      running install
      /media/master/support/pip_envs/rl/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/pickle5
      copying pickle5/__init__.py -> build/lib.linux-x86_64-cpython-38/pickle5
      copying pickle5/pickle.py -> build/lib.linux-x86_64-cpython-38/pickle5
      copying pickle5/pickletools.py -> build/lib.linux-x86_64-cpython-38/pickle5
      creating build/lib.linux-x86_64-cpython-38/pickle5/test
      copying pickle5/test/pickletester.py -> build/lib.linux-x86_64-cpython-38/pickle5/test
      copying pickle5/test/test_picklebuffer.py -> build/lib.linux-x86_64-cpython-38/pickle5/test
      copying pickle5/test/__init__.py -> build/lib.linux-x86_64-cpython-38/pickle5/test
      copying pickle5/test/test_pickle.py -> build/lib.linux-x86_64-cpython-38/pickle5/test
      running build_ext
      building 'pickle5._pickle' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/pickle5
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/media/master/support/pip_envs/rl/include -I/usr/include/python3.8 -c pickle5/_pickle.c -o build/temp.linux-x86_64-cpython-38/pickle5/_pickle.o -std=c99
      In file included from pickle5/_pickle.c:2:
      pickle5/compat.h:1:10: fatal error: Python.h: No such file or directory
          1 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pickle5

note: This is an issue with the package mentioned above, not pip.
```
I tried installing it with python 3.9 and 3.8 on Ubuntu 22.04 OS. 

Are there any additional requirements to use your library?

**Comment by simoninithomas** [comment]
Hi, it's because you're using python >3.8 , pickle5 is for python 3.6.

The first solution is to use colab. In the meantime checking if we can remove in pickle5

**Comment by simoninithomas** [comment]
You can now use version 2.1.0 and it should work 🥳

**Comment by kirilllzaitsev** [comment]
@simoninithomas Thank you! Now it's working with 3.8.
